#!/usr/bin/python

import networkx as nx
import sys
import re

g = nx.MultiDiGraph()

recipes = open("pure.list", "r")

for i in recipes:
    temp = re.split(r'\t+', i)
    goal, comp = temp[0], temp[1:]
    for item in comp:
        g.add_edge(str.strip(goal), str.strip(item))
    

#print g.edges()
#print g.number_of_edges()
    
query = sys.argv[1]

print "Query:",query
print "Recipe: "
for edge in g.edges():
    if edge[0].lower() == query.lower() :
        print " -",edge[1]
